### ISSUE TITLE
ApplicationProfile could be an aspect of prof:Profile

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/CAMSS_CSSV#1]
In CSSV, the definition of the class Application Profile matches the semantics of the "Profile" class defined in the [W3C Profiles Vocabulary](https://www.w3.org/TR/dx-prof/#Class:Profile).

We propose to enrich the CSSV's ApplicationProfile with a property "isAspectOf prof:Profile". The axiom would then look like "cssv:ApplicationProfile isAspectOf prof:Profile".

**Comment by paulakeen** [comment]
Perhaps connecting the ApplicationProfile to the prof:Profile is an overkiller of the  "core" and should be treated in a subsequent ontology covering well identified use cases. 

See issue [#3](https://github.com/SEMICeu/CAMSS_CSSV/issues/3),

**Comment by isa-camss** [comment]
Many thanks for the comment. This issue has been also discussed in the issue #5 Profiles in W3C.

**Comment by EmidioStani** [comment]
This repository is going to be archived, thus I am closing this issue.
