### ISSUE TITLE
cssv:Standard and dct:Standard

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/CAMSS_CSSV#2]
Shouldn't the CSSV classes Standard and Specification relate/reuse dct:Standard? and how?

**Comment by paulakeen** [comment]
"One possible design would be that the Standard class extended the Specification **and** the dct:Standard.

The definition could then be slightly different to one provided right now:

"A Specification with a relevant endorsement and largely used as a basis for comparison or as a reference point."

![image](https://user-images.githubusercontent.com/16134316/67899145-f9a12d80-fb61-11e9-80c9-6742c2768845.png)

**Comment by isa-camss** [comment]
Many thanks. This is a good idea and it has also been recommended by @heidivanparys in this comment https://github.com/SEMICeu/CAMSS_CSSV/issues/5#issuecomment-556034611 and also the suggestion of reusing DCMI as much as possible in issue #7.

**Comment by EmidioStani** [comment]
This repository is going to be archived, thus I am closing this issue.
