### ISSUE TITLE
Specification as an adms:Asset -> ADMS should be revamped urgently!

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/CAMSS_CSSV#4]
I do like very much the idea that the base class is an adms:Asset. This simple fact allows for:

1. to inherit many metadata that are indispensable, like version, distribution, etc,
2. to disseminate the idea that adms:Asset should be the base class for many other vocabularies and ontologies. In the context of SEMIC and ISA2, for examplel, that should be the case for DCAT, CAV, ELIS, EIRA, etc. 

The case of DCAT is very interesting in this sense: If i didn't get it wrong DCAT was developed previously to ADMS, and that would be why ADMS is just a profile of DCAT. Sorry to be blunt, but for me this is nosense. If the history had gone the opposite way, first defining ADMS and later on DCAT, Datasets would then be just one type of Asset, and not the opposite. Possibly this would also had contributed to come up with a more sensible definition of what an Asset and with a different design.

I know this public consultation space is reserved for the perfection of the CSSV, but as Asset is reused as a crucial base class I think this is a good forum to throw this challenge: ADMS should be revamped urgently, IMO the current ADMS specification is, to  say the least, misleading and cannot be seen as the fundamental building block of many other vocabularies. Which in the end hampers the semantic cross-domain interoperability.

**Comment by isa-camss** [comment]
See issue #6 for further comments on this idea of @paulakeen.

**Comment by paulakeen** [comment]
Please visit this [Issue](https://github.com/isa-camss/CAV/issues/5) created in the CAMSS CAV development: "Replace the ADMS Asset (DCAT Dataset) with W3C DCAT Resource".

**Comment by EmidioStani** [comment]
This repository is going to be archived, thus I am closing this issue.
