### ISSUE TITLE
Profiles in W3C

### ISSUE THREAD

**Issue by heidivanparys** [SEMICeu/CAMSS_CSSV#5]
The problem statement is:

> At the present stage there is not a clear definition of what a specification, a standard, a family of specifications and an **application profiles** are.

(highlighting is mine)

The W3C Dataset Exchange Working Group (DXWG) is currently writing a set of documents on profiles, see https://w3c.github.io/dxwg/profiles/ and https://www.w3.org/TR/dx-prof/

Has that input been considered? If yes: what was the conclusion?

Proposal: align with the work done in the DXWG where possible, suggest improvements to DXWG where needed.

**Comment by isa-camss** [comment]
Thank you for you comment @heidivanparys. Regarding to your comment, you can see the issue #1 where we are talking about W3C Profiles Vocabulary.

In CSSV, the definition of the class Application Profile matches the semantics of the "Profile" class defined in the W3C Profiles Vocabulary.

We propose to enrich the CSSV's ApplicationProfile with a property "isAspectOf prof:Profile". The axiom would then look like "cssv:ApplicationProfile isAspectOf prof:Profile".

**Comment by heidivanparys** [comment]
Given the fact that the Profiles Vocabulary and the Core Standards and Specifications Vocabulary are both work in progress, I think there is a unique chance to make sure that no duplicate work is done.

If cssv:ApplicationProfile is the same as prof:Profile, then CSSV should reuse prof:Profile instead of defining cssv:ApplicationProfile.

From https://w3c.github.io/dxwg/prof/:

![image](https://user-images.githubusercontent.com/11427611/69248645-e572ae00-0bac-11ea-9bab-19c4ace8daa1.png)

**Comment by heidivanparys** [comment]
An additional comment: it seems that both prof and cssv would be used to describe DCAT-AP. I am not sure what "DCAT-AP isAspectOf DCAT-AP" would mean then?

**Comment by aidig** [comment]
Creating a common language for specifications is a highly welcomed initiative!

However, as Heidi points out, the Profiles Vocabulary and the Core Standards and Specifications Vocabulary seems to be semantically overlapping...

More attention should be given to adhering to the ISA2 principle of sharing and resusing for the purpose of interoperability.

Highly agree that seeing that both vocabularies are being drafted, this presents a great potential for cooperation and alignment. 

Also, please can you elaborate on the property isAspectOf - would this be inverse of vaem:hasAspect? (http://www.linkedmodel.org/schema/vaem#hasAspect). Or are you coining a new property?

**Comment by isa-camss** [comment]
Thanks for all the inputs so far. Indeed, having one single common vocabulary for all these concepts would be great. This is why in the issue #1 @paulakeen identified that the prof:Profile could be refered to/reused by the CSSV. 

@paulakeen reuses the Publications Office CDM hasAspectOf property to mean that an Application profile as defined in the CSSV is a modality of Profile that has been defined in ISA2 as “An Application Profile is a specification that reuses terms from other standards, adding more specificity by identifying mandatory, recommended and optional elements, as well as by defining controlled vocabularies to be employed.” (https://ieeexplore.ieee.org/document/8823991). In the context of ISA2 developments, this is the classic understanding of what an Application Profile is, and we use it to elaborate our own concept and entity definition.

Having said this, @paulakeen's comment to her own issue is what the scope of a "**Core**" vocabulary should be. Which shoud lead us to sit together and brainstorm about how to proceed from now on. As we see it, the prof:Profile model should subsumed into a larger "Standards and Specifications" ontology. 

Let us discuss this also internally in ISA2 and we will come back to you asap. Many thanks for this suggestion. We sincerely adhere to it.

**Comment by paulakeen** [comment]
The OP's [Common Data Model, CDM](https://op.europa.eu/en/web/eu-vocabularies/cdm)is available from the [EU Vocabularies site](https://op.europa.eu/en/web/eu-vocabularies/).

**Comment by EmidioStani** [comment]
This repository is going to be archived, thus I am closing this issue.
