### ISSUE TITLE
Definition of specification

### ISSUE THREAD

**Issue by heidivanparys** [SEMICeu/CAMSS_CSSV#6]
The problem statement is:

> At the present stage there is not a clear definition of what a **specification**, a standard, a family of specifications and an *application profiles are.

(highlighting is mine)

The definition of specification has been discussed in work done by W3C Dataset Exchange Working Group (DXWG).

In one of the issues, see https://github.com/w3c/dxwg/issues/418 , the following definition was proposed, and is also proposed here for use in CSSV:

**specification**
detailed description of how something is, or should be, designed or made
[SOURCE: [Oxford Learner's Dictionary of Academic English](https://www.oxfordlearnersdictionaries.com/definition/academic/specification), def. 1]

If needed in CSSV, notes could be added, e.g. like the following:

**specification**
detailed description of how something is, or should be, designed or made
Note 1 to entry: (sth about that "something" in this context is called an asset)
Note 2 to entry: (sth about descriptions are usually given in the form of normative statements such as requirements and recommendations, etc.)
[SOURCE: [Oxford Learner's Dictionary of Academic English](https://www.oxfordlearnersdictionaries.com/definition/academic/specification), def. 1, modified — Notes have been added.]

As minimum, the current definition in CSVV should be updated as there is an issue with its structure: term specification is singular, but its definition is plural:

specification = agreed, descriptive and normative statements concerning an asset ❌
specification = set of agreed, descriptive and normative statements concerning an asset ✔️

**Comment by isa-camss** [comment]
Many thanks for your input. We have a lot of things to comment about this subject:

1. Similarly to what @paulakeen comments in issue #4, we also are convinced about the need of redifining and redisigning the ADMS. The fact that ADMS was defined based on DCAT is for us highly inconvenient. The concept ADMS Asset should be defined in the ADMS namespace and totally unaware of DCAT concepts like Dataset and other. As a matter of fact we think that dcat:Dataset should be an adms:Asset and not the opposite. Additionally, assets can be seen as resources, probably resulting from a Work (but not necessarly), that is available for use and brings value. Surprisingly enough, the very latest version of DCAT (https://www.w3.org/TR/vocab-dcat-2/) defines a dcat:Resource class that looks very much to our idea of what an Asset should be. The layering in adms:Resource and adms:Asset in the ADMS namespace would then provide an excellent excuse: (1) For connecting adms:Resource to the IFLA LRM model and, (2) For connecting the specialisation adms:Asset to specialise sub-properties and sub-classes of the aspects of the IFLA Work, Expression, Manifestation and Item, (3) For DCAT to reuse adms:Asset (and transitively adms:Resource). 

2. In our model specifications are specialisations of assets and therefore are also resources as would be defined in a completly revamped ADMS. As we are far from there, we have no other solution than reusing the dcat:Dataset to refer to both. But we are not happy with this, and this is why we want to atleast come up with a definition that differs from the one proposed by W3C Dataset Exchange Working Group (DXWG). 

3. Nonetheless, your suggestion plus our idea could somehow be combined into: 

- Specification= set of agreed, descriptive and normative statements about how an asset should be designed or made.

Additional Information: Statements may take the form of principles, requirements, recommendations and non-normative diagrams and examples, etc.

![image](https://user-images.githubusercontent.com/44846035/70154864-84b99a00-16b1-11ea-9306-94c294731c13.png)

**Comment by EmidioStani** [comment]
This repository is going to be archived, thus I am closing this issue.
